version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo '> npm install'
      - npm install

  build:
    commands:
      - echo '> npm run build'
      - npm run build

artifacts:
  files:
    - 'views/**/*'
    - 'build/**/*' 
    - 'package.json' 
    - 'package-lock.json'
  base-directory: '.' 
  discard-paths: no # ディレクトリ構造を維持