version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo '> npm install'
      - npm install

  build:
    commands:
      - echo '> npm run build'
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
